version: "3"
services:
  frontend:
    image: frontend
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - montauk-labs-app
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
networks:
  montauk-labs-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local